require "verde.core"
require "verde.options"
require "verde.keymaps"
require "verde.autocmds"
spec "verde.colorscheme.darkplus"
spec "verde.colorscheme.catppuccin"
spec "verde.colorscheme.github"
spec "verde.devicons"
spec "verde.treesitter"
spec "verde.mason"
spec "verde.schemastore"
spec "verde.lspconfig"
spec "verde.cmp"
spec "verde.lualine"
-- spec "verde.copilot" -- skill issue
-- spec "verde.harpoon" -- TODO: fix!!
spec "verde.autopairs"
spec "verde.illuminate"
spec "verde.whichkey"
spec "verde.neogit"
spec "verde.gitsigns"
spec "verde.gitlinker"
spec "verde.none-ls"
spec "verde.telescope"
spec "verde.alpha"
spec "verde.sleuth"
spec "verde.surround"
-- clojure specific plugins
spec "verde.jack-in"
spec "verde.conjure"
spec "verde.paredit"
-- laravel specific plugins
spec "verde.laravel"
-- rust specific plugins
spec "verde.rust"
spec "verde.crates"
-- go specific plugins
spec "verde.go"
-- debug specific plugin
spec "verde.nvim-dap"
-- Less important plugins
spec "verde.navbuddy"
spec "verde.colorizer"
spec "verde.undotree"
spec "verde.bqf"
spec "verde.nvimtree"
spec "verde.toggleterm"
spec "verde.comment"
spec "verde.navic"
spec "verde.breadcrumbs"
spec "verde.oil"
spec "verde.lsp-lense"
spec "verde.lab"
spec "verde.indent-blankline"
spec "verde.fidget"
require "verde.lazy"
