---@diagnostic disable: missing-fields
require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"lua",
		"luadoc",
		"vim",
		"vimdoc",
		"graphql",
		"markdown",
		"markdown_inline",
		"bash",
		"dockerfile",
		"html",
		"json",
		"scss",
		"xml",
		"yaml",
		"css",
		"sql",
		"go",
		"python",
		"typescript",
		"javascript",
		"java",
		"clojure",
		"rust",
		"gowork",
		"gomod",
		"gosum",
		"gotmpl",
		"comment",
	},
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = { "org" },
	},
	indent = { enable = true },
	sync_install = false,
})
